"""Initial migration

Revision ID: 28243be7f8ba
Revises: 
Create Date: 2025-02-03 21:01:29.847353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28243be7f8ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('is_vacant', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('moved_out', sa.Boolean(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_paid', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_payment')
    op.drop_table('tenant')
    op.drop_table('apartment')
    # ### end Alembic commands ###
